<img src="data/scipy_ecosystem.png" align="left" height="400" width="400" >

## Библиотека numpy

Библиотека <strong>numpy</strong> используется для различного рода математических вычислений и работы с многомерными массивами. 
Основная структура numpy - многомерный массив, который создается на основе данных пользователя. <br/> 
Для начала импортируем библиотеку: 

In [1]:
import numpy as np

## Векторы и матрицы

Для создания некоторого массива нам необходимо вызвать функцию <stong>[array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)</stong>, которая принимает на вход как раз данные в виде некоторой последовательности, например списка. 

Numpy массив можно создать, используя функцию np.array и передавая либо список для создания одномерного массива, либо список списков для создания матрицы:

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([[1, 0, 3],[1, 5, 4]])

In [5]:
b

array([[1, 0, 3],
       [1, 5, 4]])

После создания массива мы можем посмотреть как он выглядит. Видим, что это некоторый тип <strong>array</strong>, обладающий следующими свойствами: можно посмотреть какой тип данных хранится в массиве и какая размерность у массива. <br/>
С помощью атрибута <strong>[dtype](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)</strong> можно узнать какие данные хранятся в массиве. <br/>
Тип данных может определяться автоматически на основе того, какие есть входные данные, а также можно его указывать при создании массива как дополнительный аргумент.

In [6]:
b.dtype

dtype('int32')

In [7]:
c = np.array([[1, 0, 3],[1, 5, 4]], dtype=np.int64)

In [8]:
c

array([[1, 0, 3],
       [1, 5, 4]], dtype=int64)

In [9]:
c.dtype

dtype('int64')

Размер массива с помощью метода [shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) - возвращается количество строк и столбцов

In [10]:
b.shape

(2, 3)

Индексация для двумерного массива происходит по двум осям: первый индекс по строкам, второй по столбцам.

In [11]:
b

array([[1, 0, 3],
       [1, 5, 4]])

In [12]:
b[1, 1]

5

### Создание массивов

In [13]:
d = np.zeros(3)

In [14]:
d

array([0., 0., 0.])

Массив, состоящий только из единиц:

In [15]:
b = np.ones((5, 7))
b

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

Массив, состоящий из констант:

In [16]:
c = np.full((3, 4), 7)
c

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

Единичная матрица:

In [17]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

Массив, заполненный случайными числами:

In [18]:
e = np.random.random((5, 2)) 
e

array([[0.83914799, 0.16231205],
       [0.23505673, 0.77472245],
       [0.65372432, 0.55532263],
       [0.09984935, 0.36160633],
       [0.38829908, 0.72665275]])

### Индексация в массивах

<img src="data/numpy.png" align="left" height="500" width="500" >

In [19]:
a = np.array([[0, 1, 2, 3, 4, 5], 
              [10, 11, 12, 13, 14, 15], 
              [20, 21, 22, 23, 24, 25], 
              [30, 31, 32, 33, 34, 35], 
              [40, 41, 42, 43, 44, 45], 
              [50, 51, 52, 53, 54, 55]])

In [20]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [21]:
a[:2, 1:3] 

array([[ 1,  2],
       [11, 12]])

In [22]:
a[1, :]

array([10, 11, 12, 13, 14, 15])

In [23]:
a[1:2, :]

array([[10, 11, 12, 13, 14, 15]])

Фильтрация значений происходит следующим образом - сначала создается маска из значений True/False, затем эта маска передается как индексы:

In [24]:
a = np.array([[1, 4], [3, 49], [5, 6]])
a

array([[ 1,  4],
       [ 3, 49],
       [ 5,  6]])

In [25]:
idx = (a > 3)
idx

array([[False,  True],
       [False,  True],
       [ True,  True]])

In [26]:
a[idx]

array([ 4, 49,  5,  6])

In [27]:
a[a > 4]

array([49,  5,  6])

### Операции с векторами

Можно использовать встроенные функции <strong>numpy</strong> для математических операций - например [np.add](https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html) для сложения векторов. Напомним, что данные операции производятся поэлементно:

In [28]:
x = np.array([[1, 1],[6, 4]], dtype=np.float64) # можно дополнительно указать тип данных при создании массива
y = np.array([[5, 2],[1, 8]], dtype=np.float64)

In [29]:
print(x + y)
print(np.add(x, y))

[[ 6.  3.]
 [ 7. 12.]]
[[ 6.  3.]
 [ 7. 12.]]


Либо можно использовать операторы сложения/умножения:

In [30]:
x - y

array([[-4., -1.],
       [ 5., -4.]])

In [31]:
np.subtract(x, y)

array([[-4., -1.],
       [ 5., -4.]])

In [32]:
x * y

array([[ 5.,  2.],
       [ 6., 32.]])

In [33]:
x / y

array([[0.2, 0.5],
       [6. , 0.5]])

In [34]:
np.divide(x, y)

array([[0.2, 0.5],
       [6. , 0.5]])

In [35]:
np.multiply(x, y)

array([[ 5.,  2.],
       [ 6., 32.]])

### Перемножение матриц

Для перемножения векторов и матриц используется метод [dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html):

In [36]:
v = np.array([19, 1])
w = np.array([11, 22])

In [37]:
print(v.dot(w))
print(np.dot(v, w))

231
231


In [38]:
print(x.dot(v))

[ 20. 118.]


In [39]:
x.dot(y)

array([[ 6., 10.],
       [34., 44.]])

Документация:

[From Python to Numpy](http://www.labri.fr/perso/nrougier/from-python-to-numpy/)

[NumPy: creating and manipulating numerical data](http://scipy-lectures.org/intro/numpy/index.html)

[про numpy на русском языке](http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy?sortcol=0&table=9&up=0)




### Рекомендую книгу:

<a href="https://habr.com/ru/company/piter/blog/339766/"><img src="data/ebook.jpeg" align="left" height="280" width="280" ></a>